import type { NextPage } from "next";
import Head from "next/head";
import { RandomFox } from "../components/RandomFox"

const randomNumber = () => Math.floor(Math.random() * 123) + 1;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>React Project</title>
        <meta name="description" content="Generated by Erika" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1 className="text-3xl font-bold underline">
      Welcome to my React project
      </h1>
      <RandomFox image={`https://randomfox.ca/images/${randomNumber()}.jpg`}/>
      </main>
      <footer>
      </footer>
    </div>
  );
};

export default Home;
