'use client'

import { MouseEventHandler, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { random } from "lodash";
import { LazyImage } from "../components/LazyImage";

const randomNumber = () => random(0, 123);
const generateId = (): string => {
  return (
    Math.random().toString(36).substring(2, 15) +
    Math.random().toString(36).substring(2, 15)
  );
};

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<IFoxItem>>([]);

  const addNewFox : MouseEventHandler<HTMLButtonElement> = () => {
   
    const newImageItem = { 
      id: generateId(), 
      url: `https://randomfox.ca/images/${randomNumber()}.jpg`
    };

    setImages([...images, newImageItem]);
    //window.plausible("add_fox");
  };

  return (
    <div>
      <Head>
        <title>React Project</title>
        <meta name="description" content="Generated by Erika" />
        <link rel="icon" href="/favicon.ico" />
        <script 
        defer data-domain="erikamelt.github.io" 
        src="https://plausible.io/js/script.js">
        </script>
      </Head>

      <main className="text-center">
      <PageContent />
      <div className="m-4">
        <button 
          onClick={addNewFox}
          className="py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
        Add New Fox
        </button>
        </div>
      {images.map(({id, url}, index) => (
          <div className="p-4" key={id}>
            <LazyImage 
              src={url}
              width={320} 
              height= "auto" 
              title="Random Fox"
              className="mx-auto rounded-md bg-gray-300"
              onClick={() => {
                console.log("holi!");
              }}
              onLazyLoad={(img) => {
                console.log(`Image #${index + 1} cargada. Nodo:`, img);
              }}

            />
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};


function PageContent() {
  return (
    <div className="pt-10 pb-4 px-4 sm:px-6 lg:px-8">
      <p className="text-base leading-6 text-indigo-600 font-semibold tracking-wide uppercase">
        React and TypeScript Course
      </p>
      <h3 className="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl sm:leading-10">
        Lazy Loading Image Component
      </h3>
      <div className="max-w-xl mx-auto text-xl text-gray-500 leading-7">
        <p className="mt-4">
          React component to load images using lazy loading.
        </p>
        <p className="mt-4">✨✨</p>
        <p className="mt-4">
          The images wont be loaded until the component is mounted.
        </p>
        <p className="mt-4">✨✨</p>
      </div>
    </div>
  );
}

export default Home;
