'use client'

import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { RandomFox } from "../components/RandomFox";

const randomNumber = () => Math.floor(Math.random() * 123) + 1;
const generateId = () => Math.random().toString(36).substr(2,9);

type ImageItem = {id: string, url: string};

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<ImageItem>>([
    { id:generateId(), url:`https://randomfox.ca/images/${randomNumber()}.jpg` }, 
    { id:generateId(), url:`https://randomfox.ca/images/${randomNumber()}.jpg` }, 
    { id:generateId(), url:`https://randomfox.ca/images/${randomNumber()}.jpg` }, 
    { id:generateId(), url:`https://randomfox.ca/images/${randomNumber()}.jpg` }, 
  ]);

  return (
    <div>
      <Head>
        <title>React Project</title>
        <meta name="description" content="Generated by Erika" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1 className="text-3xl font-bold underline">
      Welcome to my React project
      </h1>
      {images.map(({id, url}) => (
          <div className="p-4" key={id}>
            <RandomFox image={url} />
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
